#!/usr/bin/env bash
# This Bash script checks the disk usage of the home directory
# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
handle_sigquit() {
    echo "Terminating..."
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap SIGTERM signal and call handle_sigterm function
trap 'handle_sigterm' SIGTERM

# Trap SIGINT signal and call handle_sigint function
trap 'handle_sigint' SIGINT

# Trap SIGQUIT signal and call handle_sigquit function
trap 'handle_sigquit' SIGQUIT

# Write the PID to the file
echo "$$" > /var/run/myscript.pid

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
