#!/usr/bin/env bash
# This Bash script checks the disk usage of the home directory
# Get the PID of the process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
    # Send SIGINT signal to stop the process
    kill "$pid"
    echo "Process with PID $pid stopped."
else
    echo "Process not found."
fi
