#!/usr/bin/env bash
# This Bash script checks the disk usage of the home directory
# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM signal and call handle_sigterm function
trap 'handle_sigterm' SIGTERM

# Function to stop the "7-highlander" process
stop_highlander() {
    pkill -f "7-highlander"
    echo "7-highlander process stopped."
}

# Trap SIGINT signal and call stop_highlander function
trap 'stop_highlander' SIGINT

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
