#!/usr/bin/env bash
# This Bash script checks the disk usage of the home directory
MANAGE_SCRIPT="$SCRIPT_DIR/manage_my_process"
# Ensure the file exists before starting
touch /tmp/my_process

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Loop indefinitely
while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done

case "$1" in
    start)
        "$MANAGE_SCRIPT" start
        ;;
    stop)
        "$MANAGE_SCRIPT" stop
        ;;
    restart)
        "$MANAGE_SCRIPT" restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
