#!/usr/bin/env bash
# Bash script to display username, user id, and home directory path from /etc/passwd
while IFS=: read -r username _ userid _ _ homedir _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
done < /etc/passwd
