#!/usr/bin/env bash
# Bash script to create a fictional story based on /etc/passwd
while IFS=: read -r username _ userid groupid _ user_info homedir shell
do
    info=$(grep -oP "(?<=GECOS=).*(?=,)" <<< "$user_info")
    password=$(grep -oP "(?<=PASSWORD=).*(?=,)" <<< "$user_info")
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
    echo ""
done < /etc/passwd
