#!/usr/bin/env bash
# Bash script to display "Best School" 10 times, with "Hi" on a new line for the 9th iteration
counter=0
while [ $counter -lt 10 ]
do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
