#!/usr/bin/env bash
# Bash script to display time for 12 hours and 59 minutes
hour=0
minute=1

while [ $hour -le 12 ] && [ $minute -le 59 ]
do
    printf "%02d:%02d\n" $hour $minute
    if [ $minute -eq 59 ]; then
        ((hour++))
        minute=0
    else
        ((minute++))
    fi
done | head -n 70
