#!/usr/bin/env bash
# Bash script to display the content of the current directory in a list format,
# where only the part of the name after the first dash is displayed
for file in *
do
    if [[ ! $file =~ ^\. && ( -f $file || -d $file ) ]]; then
        name=$(echo "$file" | cut -d '-' -f 2-
        echo "$name"
    fi
done
